objects/ClaytonCopadoIntegration__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>ApiPassword__c</fullName>
        <label>ApiPassword</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ApiUser__c</fullName>
        <label>ApiUser</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ClientId__c</fullName>
        <label>ClientId</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ClientSecret__c</fullName>
        <label>ClientSecret</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>ClaytonCopadoIntegration</label>
</CustomObject>

classes/ClaytonTokenUtils.cls
public with sharing class ClaytonTokenUtils {

    public static String getAccessToken() {

        ClaytonCopadoIntegration__c claytonCopado = ClaytonCopadoIntegration__c.getInstance();

        String OAutAuthURL = 'https://staging.claytonapp.com/oauth/token'; 
        HttpRequest request = new HttpRequest();
        request.setEndpoint( OAutAuthURL );
        request.setMethod('POST');
        request.setHeader('Content-Type','application/x-www-form-urlencoded');
        
        String scope = EncodingUtil.urlEncode('read write','UTF-8');
        String username = EncodingUtil.urlEncode(claytonCopado.ApiUser__c,'UTF-8');
        String password = EncodingUtil.urlEncode(claytonCopado.ApiPassword__c,'UTF-8');

        String body = 'grant_type=password&client_id='+claytonCopado.ClientId__c+'&client_secret='+claytonCopado.ClientSecret__c+'&username='+username+'&password='+password+'&scope='+scope;
        
        request.setBody(body);
        Http http = new Http();
        HttpResponse response = http.send(request);
        ClaytonToken claytonToken = (ClaytonToken) JSON.deserialize(response.getBody(), ClaytonToken.class);
        return claytonToken.access_token;

    }

}